apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/name1: nginx
    app.kubernetes.io/name2: nginx
spec:
  containers:
  - name: myapp
    image: nginx:latest
    ports:
      - containerPort: 80
